spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/user/**

        - id: BlogService
          uri: ${BLOG_SERVICE_URL}
          predicates:
            - Path=/api/v1/blog/**

#        - id: CommentService
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/comment/**
#
#        - id: FriendService
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/v1/friend/**
#
        - id: LikeService
          uri: ${LIKE_SERVICE_URL}
          predicates:
            - Path=/api/v1/like/**
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
  main:
    web-application-type: reactive
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      access: unrestricted